# cargo build --release --target=x86_64-unknown-linux-musl
[package]
name = "accinfo"
version = "0.1.0"
authors = ["kiven <kivensoft@gmail.com>"]
edition = "2021"
description = "account information management system"
repository = "https://github.com/kivensoft/accinfo_rust"

[profile.release]
opt-level = 'z'  # Optimize for size
lto = true
strip = true
codegen-units = 1
incremental = false
panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26", features = [ "full" ] }
hyper = { version = "0.14", features = [ "runtime", "http1", "server", "client", ] }
bytes = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
anyhow = "1.0"
log = "0.4"
chrono = "0.4"
async-trait = "0.1"
lazy_static = "1.4"
asynclog = { version = "1.0", path = "asynclog" }
appconfig = { version = "1.0", path = "appconfig" }
ansicolor = { version = "1.0", path = "ansicolor" }
